### ISSUE TITLE
Material Editor Doesn't Refresh After Cutting Wires

### ISSUE THREAD

**Issue by CoolOppo** [pdlogingithub/UE4-Node-Graph-Assistant#10]

**Comment by pdlogingithub** [comment]
Can you be more specific?

**Comment by CoolOppo** [comment]
Whenever I use the scissors to remove a connection between two material nodes, the material graph isn't marked dirty, so it acts the same as if the nodes were still connected to one another in the preview.

**Comment by CoolOppo** [comment]
The extension Graph Formatter had a similar issue that was fixed in this commit:

https://github.com/howaajin/graphformatter/commit/56fb8783cfd3242b789a2dc0ba3c94c21ce8ca2f

**Comment by pdlogingithub** [comment]
Oh I see,will fix that,thanks for the notice

**Comment by pdlogingithub** [comment]
For now you can click the preview button in the tool bar twice to force a refresh.

**Comment by pdlogingithub** [comment]
fixed in ver 1.7
