### ISSUE TITLE
Feature Request: Connect two or more selected nodes

### ISSUE THREAD

**Issue by uexilon** [pdlogingithub/UE4-Node-Graph-Assistant#11]
Hey

Thank you for this nice plugin. It's really handy.
While using it we ran into a situation where we thought: "That would be nice to have". One of those "nice to have" things would be the ability to connect selected nodes by using a shortcut. This would be really helpful if you got quite a few nodes close to each other with compatible pins (all floats, ints, etc.). Being able to just select the nodes we want to connect would be a bit easier and faster than wiring them in or trying to correctly position them for the auto connect feature.
Usage Example:
![image](https://user-images.githubusercontent.com/17800777/63209626-8e5bc980-c0e3-11e9-847f-cb699185875e.png)

Thank you for your work!

**Comment by pdlogingithub** [comment]
This feature is added in version 1.7,press alt+c or any shortcut you set to connect selected nodes,the result will follow the patttern of "every shortest path".
