### ISSUE TITLE
Insert node operation appears to have never fully finished

### ISSUE THREAD

**Issue by HughMacdonald** [pdlogingithub/UE4-Node-Graph-Assistant#18]
Hi,

First off, I started using this plugin yesterday, and find it incredibly useful.

This morning I had just connected a couple of nodes using Auto Connect. I compiled the blueprint and went to start PIE, and it told me "Can't Play In Editor when performing Insert node operation".

**Comment by pdlogingithub** [comment]
got that,will investigate

**Comment by Meguido** [comment]
Started happening to me today using 4.22.3 version

**Comment by pdlogingithub** [comment]
I sumit a fix,please update the plugin in launcher to see if the problem is solved.

**Comment by saurabhcool001** [comment]
To restarting the engine solved my issues. Maybe you can try too same.
