### ISSUE TITLE
Feature request: Node deletion and insertion

### ISSUE THREAD

**Issue by SkaveRat** [pdlogingithub/UE4-Node-Graph-Assistant#2]
Something I really miss is a feature to delete a node but reconnect input and output exec wires.

e.g. I want to delete the debug-print I inserted between two nodes, press shift-delete and the node gets deleted and the input and output wire connected

related: inserting a node "on" a wire. e.g. I want to insert a temporary debug node between two nodes. I drag the debug node on a wire, the wire gets hilighted and on release gets inserted between nodes.

**Comment by pdlogingithub** [comment]
Hi, sorry to reply so late,but I'm now working on these features, hope to release soon.

**Comment by pdlogingithub** [comment]
check out the new user guide:
https://github.com/pdlogingithub/UE4-Node-Graph-Assistant/blob/master/README.md

it may take a while before epic approved my submit and update the market place.
