### ISSUE TITLE
Crashed during NGA code

### ISSUE THREAD

**Issue by HughMacdonald** [pdlogingithub/UE4-Node-Graph-Assistant#20]
I just had a crash that seems to be NGA related.

Here's the crash log:

Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Containers/Array.h] [Line: 614] Array index out of bounds: 1 from an array of size 1

UE4Editor_Core!FWindowsErrorOutputDevice::Serialize() [d:\build\++ue4\sync\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
UE4Editor_Core!FOutputDevice::LogfImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
UE4Editor_Core!AssertFailedImplV() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
UE4Editor_Core!FDebug::CheckVerifyFailedImpl() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:445]
UE4Editor_UnrealEd!DispatchCheckVerify<void,<lambda_2519354e8d7c841a0a01de7e75d057d0> >() [d:\build\++ue4\sync\engine\source\runtime\core\public\misc\assertionmacros.h:165]
UE4Editor_UnrealEd!UTransBuffer::Cancel() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editortransaction.cpp:1248]
UE4Editor_NodeGraphAssistant!<lambda_9d8bcbb01b314107d512b77a8be9f2bb>::operator()() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\nodegraphassistant\source\private\ngainputprocessor.cpp:1462]
UE4Editor_NodeGraphAssistant!NGAInputProcessor::Tick() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\nodegraphassistant\source\private\ngainputprocessor.cpp:2698]
UE4Editor_Slate!FSlateApplication::InputPreProcessorsHelper::Tick() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:7678]
UE4Editor_Slate!FSlateApplication::FinishedInputThisFrame() [d:\build\++ue4\sync\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:1637]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:4235]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:173]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:147]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:279]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by pdlogingithub** [comment]
I sumit a fix,please update the plugin in launcher to see if the problem is solved.
