### ISSUE TITLE
[Feature Request] TAB keyboard button for opening the context menu.

### ISSUE THREAD

**Issue by iartist93** [pdlogingithub/UE4-Node-Graph-Assistant#22]
Hello,
Please can you add the support for the [TAB] keyboard button to show the context menu for adding new nodes instead of using the RMB only?
It would be a cool addition as most node based packages like Houdini and substance use it.

Thanks.

**Comment by pdlogingithub** [comment]
I will take a look.

**Comment by pdlogingithub** [comment]
Well it seems that UE 426 has this action by default now,have fun with it.
