### ISSUE TITLE
PCG (integration-state with procedural-content-generation)

### ISSUE THREAD

**Issue by BoomRaccoon** [pdlogingithub/UE4-Node-Graph-Assistant#31]
Just curious if you are working on the PCG side because I encountered some issues.
Maybe you have already started to look into it and could give an estimate?

Also, is this the best place to report bugs?

**Comment by pdlogingithub** [comment]
Not gonna invest much on pcg graph,but new update has fix some crach with pcg graph,most function will work just fine with pcg graph,maybe some will be off.
